### Implementation of Word Embedding

In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot #type: ignore
from tensorflow.keras.layers import Embedding #type: ignore
from tensorflow.keras.preprocessing.sequence import pad_sequences #type: ignore
from tensorflow.keras.models import Sequential #type: ignore

In [2]:
# Sentences
sentence = [
    "The glass of milk",
    "The glass of juice",
    "I am a good boy",
    "I am a good developer",
    "Understand the meaning of words",
    "Your videos are good"
]

In [3]:
# Define the vocabulary size
voc_size = 10000

In [4]:
# One Hot  representation
onehot_rep = [one_hot(words, voc_size) for words in sentence]

In [5]:
onehot_rep

[[1775, 7811, 8196, 1668],
 [1775, 7811, 8196, 9728],
 [7606, 1428, 8672, 4512, 392],
 [7606, 1428, 8672, 4512, 1751],
 [2993, 1775, 4106, 8196, 220],
 [6645, 9229, 6355, 4512]]

In [6]:
# Word embedding representation
sentence_length = 8

In [11]:
embedded_docs = pad_sequences(onehot_rep, padding="pre", maxlen=sentence_length)

In [12]:
print(embedded_docs)

[[   0    0    0    0 1775 7811 8196 1668]
 [   0    0    0    0 1775 7811 8196 9728]
 [   0    0    0 7606 1428 8672 4512  392]
 [   0    0    0 7606 1428 8672 4512 1751]
 [   0    0    0 2993 1775 4106 8196  220]
 [   0    0    0    0 6645 9229 6355 4512]]


In [13]:
# Feature representation
dimension = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size, dimension, input_length=sentence_length))

In [15]:
model.compile("adam", "mse")

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 157ms/step


array([[-0.02195927,  0.04396081,  0.03821173, -0.03409791,  0.04638107,
        -0.01982251, -0.03657085, -0.01002972, -0.02949348,  0.00813063],
       [-0.02195927,  0.04396081,  0.03821173, -0.03409791,  0.04638107,
        -0.01982251, -0.03657085, -0.01002972, -0.02949348,  0.00813063],
       [-0.02195927,  0.04396081,  0.03821173, -0.03409791,  0.04638107,
        -0.01982251, -0.03657085, -0.01002972, -0.02949348,  0.00813063],
       [-0.02195927,  0.04396081,  0.03821173, -0.03409791,  0.04638107,
        -0.01982251, -0.03657085, -0.01002972, -0.02949348,  0.00813063],
       [-0.01786949, -0.02097049, -0.02173296, -0.01480198,  0.03173487,
         0.01885131, -0.03201474, -0.02242458, -0.03476778,  0.00864279],
       [-0.02706891,  0.04235205,  0.02305828,  0.02407589, -0.03595661,
         0.02485759,  0.01181309,  0.04595983,  0.02157499, -0.03650215],
       [-0.03171765, -0.00637226, -0.0005663 ,  0.03152401, -0.00289174,
        -0.02422032, -0.00142592,  0.00608901